services:
  db:
    image: ${MYSQL_IMAGE}
    env_file:
      - .env
    restart: always
#dbports-start
    ports:
      - ${MYSQL_PORT}:3306
#dbports-end
    volumes:
      - ./mysql/data/mysql:/var/lib/mysql
      - ./mysql/data/log:/var/log/mysql
      - ./mysql/conf.d/:/etc/mysql/conf.d
      - ./mysql/init/:/docker-entrypoint-initdb.d
    networks:
      myrdb:
        ipv4_address: ${IP_ADDRESS_PREFIX}.2
#phpmyadmin-start
  pma:
    image: phpmyadmin
    restart: always
    ports:
      - 127.0.0.1:${PHPMYADMIN_PORT}:80
    environment:
      - PMA_HOST=db
    networks:
      myrdb:
        ipv4_address: ${IP_ADDRESS_PREFIX}.3
#phpmyadmin-end
networks:
  myrdb:
    ipam:
      driver: default
      config:
        - subnet: ${IP_ADDRESS_PREFIX}.0/24