services:
  db:
    image: ${MYSQL_IMAGE}
    restart: always
    ports:
      - ${MYSQL_PORT}:3306
    env_file:
      - ./mysql.env
    volumes:
      - ./mysql/data/:/var/lib/mysql
      - ./mysql/log/:/var/log/mysql
      - ./mysql/conf.d/:/etc/mysql/conf.d
      - ./mysql/init/:/docker-entrypoint-initdb.d
    networks:
      myrdb:
        ipv4_address: 172.22.22.2
#phpmyadmin-start
  pma:
    image: phpmyadmin
    restart: always
    ports:
      - 127.0.0.1:${PHPMYADMIN_PORT}:3306
    environment:
      - PMA_HOST=db
    networks:
      myrdb:
        ipv4_address: 172.22.22.3
#phpmyadmin-end
networks:
  myrdb:
    ipam:
      driver: default
      config:
        - subnet: 172.22.22.0/25