#!/bin/bash

if [ -n "$MYSQL_ROOT_PASSWORD" ] && [ -n "$MYSQL_REPLICA_USER" ] && [ -n "$MYSQL_REPLICA_PASSWORD" ]; then
  echo "Creating replica user"
  mysql -h localhost -u root -p"$MYSQL_ROOT_PASSWORD" \
   -e "
   SET SQL_LOG_BIN=0;
   CREATE USER '$MYSQL_REPLICA_USER'@'%' IDENTIFIED BY '$MYSQL_REPLICA_PASSWORD';
    GRANT REPLICATION REPLICA ON *.* TO '$MYSQL_REPLICA_USER'@'%';
     GRANT CONNECTION_ADMIN ON *.* TO '$MYSQL_REPLICA_USER'@'%';
     GRANT BACKUP_ADMIN ON *.* TO '$MYSQL_REPLICA_USER'@'%';
     GRANT GROUP_REPLICATION_STREAM ON *.* TO '$MYSQL_REPLICA_USER'@'%';
     SET SQL_LOG_BIN=1;
     ";
fi
